apiVersion: apps/v1
kind: Deployment

metadata:
  name: kumarans-mlapp-deployment


spec:
  replicas: 2
  
  selector:
    matchLabels:
      app: kumarans-mlapp
  
  template:
    metadata:
      labels:
        app: kumarans-mlapp
        
    spec:
      containers:
      - name: vinay-mlapp-container
        image: vinaykarumuri15/vinay_mlops:latest
        ports:
        - containerPort: 5000