apiVersion: v1
kind: Service
metadata:
  name: mlapp-service
spec:
  selector:
    app: mlapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  #type: LoadBalancer # For Cloud
  type: ClusterIP # For GKE
