apiVersion: apps/v1
kind: Deployment

metadata:
  name: mlapp-deployment
  labels:
    app: mlapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlapp
  template:
    metadata:
      labels:
        app: mlapp
    spec:
      containers:
      - name: mlapp-container
        image: ssadcloud/mlapp:latest                                 # DockerHub
        #image: 932589472370.dkr.ecr.us-east-2.amazonaws.com/mlapp      # AWS ECR
        ports:
        - containerPort: 5000
